MODEL:
  NAME: sparse_swin_small_3.5G_82.548
  SWIN:
    APE: False
    DEPTHS: [2, 2, 18, 2]
    EMBED_DIM: 96
    IN_CHANS: 3
    MLP_RATIO: 4.0
    NUM_HEADS: [3, 6, 12, 24]
    PATCH_NORM: True
    PATCH_SIZE: 4
    QKV_BIAS: True
    QK_SCALE: None
    SVD_CONFIG: []
    WINDOW_SIZE: 7
  TYPE: sparse_swin
NAS:
  INIT_CONFIG: [[2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [1, 4], [1, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [1, 4], [2, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [1, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [2, 4], [2, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [4, 4], [2, 4], [1, 4], [1, 4]]
  NUM_CHOICES_BLOCKS: 96
  PER_CAND_AFFINE: False
  PROXY:
    ENABLE: False
    IMG_PER_CLASSES: 1
  SAMPLE_POLICY:
    CAND_POOL_SIZE: 1000
    ENABLE_CAND_POOL: False
    ENABLE_EPS: True
    EPS1:
      FIX_EPOCHS: 0
      MAX: 0.0
      MIN: 0.0
      PATIENT_EPOCHS: 0
    EPS2:
      FIX_EPOCHS: 10
      MAX: 1.0
      MIN: 0.5
      PATIENT_EPOCHS: 10
    FILTERED_POLICY: None
    NUM_KEPT_SUBNETS: 1
    NUM_SAMPLE_SUBNETS: 1
  SEARCH_SPACE: [[[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[1, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[2, 4]], [[1, 4]], [[4, 4]], [[2, 4]], [[1, 4]], [[1, 4]]]
  TARGET_COMP_RATIO: 0.5
  TEST_CONFIG:
    TEST_SUBNET: [[2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [1, 4], [1, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [1, 4], [2, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [1, 4], [1, 4], [1, 4], [2, 4], [2, 4], [1, 4], [2, 4], [2, 4], [2, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [2, 4], [2, 4], [2, 4], [1, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [2, 4], [1, 4], [4, 4], [2, 4], [1, 4], [1, 4]]
    UNIFORM_SUBNETS: []

