MODEL:
  TYPE: sparse_deit
  NAME: sparse_deit_base_baseline
  DEIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    PATCH_SIZE: 16

  DROP_PATH_RATE: 0.1

TRAIN:
  EPOCHS: 150
  WARMUP_EPOCHS: 5
  BASE_LR: 5e-5
  MIN_LR: 1e-6
  WEIGHT_DECAY: 0.05

AUG:
  MIXUP: 0.0
  CUTMIX: 0.0

SAVE_FREQ: 5

NAS:
  NUM_CHOICES_BLOCKS: 48
  SEARCH_SPACE: [[[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]], [[2, 4]]]
  PER_CAND_AFFINE: False
  TARGET_COMP_RATIO: 1.0
  SAMPLE_POLICY:
    EPS1:
      MIN: 0.0
      MAX: 0.0
    EPS2:
      MIN: 1.0
      MAX: 1.0
      PATIENT_EPOCHS: 10
      FIX_EPOCHS: 10
    NUM_SAMPLE_SUBNETS: 1
    NUM_KEPT_SUBNETS: 1
    FILTERED_POLICY : None
    ENABLE_CAND_POOL : False

  TEST_CONFIG:
    UNIFORM_SUBNETS: [[2, 4]]

  INIT_CONFIG: [[2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4], [2, 4]]